#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcacard
Version  : 2.8.1
Release  : 3
URL      : https://www.spice-space.org/download/libcacard/libcacard-2.8.1.tar.xz
Source0  : https://www.spice-space.org/download/libcacard/libcacard-2.8.1.tar.xz
Summary  : CAC (Common Access Card) library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libcacard-lib = %{version}-%{release}
Requires: libcacard-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libpcsclite)
BuildRequires : pkgconfig(libpkcs11-helper-1)
BuildRequires : pkgconfig(nss)

%description
# libcacard
[![pipeline status](https://gitlab.freedesktop.org/spice/libcacard/badges/master/pipeline.svg)](https://gitlab.freedesktop.org/spice/libcacard/commits/master)
[![coverage report](https://gitlab.freedesktop.org/spice/libcacard/badges/master/coverage.svg)](https://libcacard.freedesktop.org/)
[![cii best practices](https://bestpractices.coreinfrastructure.org/projects/3465/badge)](https://bestpractices.coreinfrastructure.org/en/projects/3465)
[![Fuzzing Status](https://oss-fuzz-build-logs.storage.googleapis.com/badges/libcacard.svg)](https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:libcacard)

%package dev
Summary: dev components for the libcacard package.
Group: Development
Requires: libcacard-lib = %{version}-%{release}
Provides: libcacard-devel = %{version}-%{release}
Requires: libcacard = %{version}-%{release}

%description dev
dev components for the libcacard package.


%package lib
Summary: lib components for the libcacard package.
Group: Libraries
Requires: libcacard-license = %{version}-%{release}

%description lib
lib components for the libcacard package.


%package license
Summary: license components for the libcacard package.
Group: Default

%description license
license components for the libcacard package.


%prep
%setup -q -n libcacard-2.8.1
cd %{_builddir}/libcacard-2.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629480365
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1629480365
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcacard
cp %{_builddir}/libcacard-2.8.1/COPYING %{buildroot}/usr/share/package-licenses/libcacard/c5041828c23a816cc38e662b61032e959cb86893
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/cacard/cac.h
/usr/include/cacard/card_7816.h
/usr/include/cacard/card_7816t.h
/usr/include/cacard/eventt.h
/usr/include/cacard/libcacard.h
/usr/include/cacard/vcard.h
/usr/include/cacard/vcard_emul.h
/usr/include/cacard/vcard_emul_type.h
/usr/include/cacard/vcardt.h
/usr/include/cacard/vevent.h
/usr/include/cacard/vreader.h
/usr/include/cacard/vreadert.h
/usr/include/cacard/vscard_common.h
/usr/lib64/libcacard.so
/usr/lib64/pkgconfig/libcacard.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcacard.so.0
/usr/lib64/libcacard.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcacard/c5041828c23a816cc38e662b61032e959cb86893
